### ISSUE TITLE
Discuss <explicit>

### ISSUE THREAD

**Issue by riedde** [music-encoding/metadata-ig#14]
On todays IG meeting we couldn't figure out how to describe this element in the guidelines (chap. 3) because we have no specialists of medieval music in our group. So we decided to ask the community for examples an explanations. Thanks to @rettinghaus for bringing this to the mensural-ig.

**Comment by ahankinson** [comment]
What is the issue with the current description of `explicit`?

Here is the element description for TEI: https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-explicit.html

Here are the expanded guidelines for manuscript description in TEI: https://msdesc.github.io/consolidated-tei-schema/msdesc.html#rubrics-etc

Here is some example TEI coding with `<explicit>` as description: https://github.com/bodleian/medieval-mss/blob/master/collections/Lat_misc/MS_Lat_misc_e_79.xml#L41-L152

**Comment by rettinghaus** [comment]
The problem with explicit is, in MEI we would expect `<explicit>` to behave like `<incipit>`. Ar least this it works in TEI, where they are both part of `[model.msQuoteLike](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.msQuoteLike.html)`. In MEI one is part in [model.incipLike](https://music-encoding.org/guidelines/dev/model-classes/model.incipLike.html), the other in [model.physDescPart](https://music-encoding.org/guidelines/dev/model-classes/model.physDescPart.html). 

Moving `<explicit>` simply to [model.incipLike](https://music-encoding.org/guidelines/dev/model-classes/model.incipLike.html) will not work, because we have here `[incipText](https://music-encoding.org/guidelines/dev/elements/incipText.html)` and `[incipCode](https://music-encoding.org/guidelines/dev/elements/incipCode.html)`. Introducing a new `model.explicitLike` seems like shooting sparrows with cannons.

As far as I can see `<incipit>` is thought through and works very well in MEI, so I wouldn't try to change anything here. Also it is very common in music catalogues to have incipits there, which is far less the case when it comes to the ending of a piece. A easy solution would then be to drop `explicit` entirely and state that this would be something for a customization.

Another approach could be to rename `incipit` into `excerpt`, because that is what we actually encode there. Then something like a `@form` could indicate where this excerpt comes from ("incipit"/"explicit" or "start" / "within" / "end").

**Comment by doerners** [comment]
metadate IG meeting 2022-03-17: We agreed that use cases for `<explicit>` are very uncommon/rare. For now the IG proposes to depricate `<explicit>` and eventually remodel `<incip>` into `<excerpt>`. @rettinghaus please prepare a PR :)

**Comment by rettinghaus** [comment]
PR has been opened. Closing this.

**Comment by riedde** [comment]
I have heard about closing keywords and maybe they are working across repos. So next time we could try to use them in a PR message like `closes music-encoding/metadata-ig#14` so in the best case the issue will be closed by merging the PR.

**Comment by rettinghaus** [comment]
@riedde You are right, but I'm not sure this is actually working across repos. Also this ticket was only about "discussion", and that already happened. 😉

**Comment by riedde** [comment]
@rettinghaus that's all fine :) Just to keep this on mind for the future ;)
